language: go
go:
  - "1.6"
  - "1.7.x"
  - "master"
before_install:
  - sudo add-apt-repository ppa:masterminds/glide && sudo apt-get update
  - sudo apt-get install glide
install: make bootstrap
script: make test
