version: "3.0"
services:
  mflowd:
    image: "mflowd:latest"
    ports:
      - "6666:6666"
    restart: "always"
    depends_on:
        - prometheus
    environment:
        - MFLOWD_SUB=${MFLOWD_SUB}
        - MFLOWD_VERBOSE=${MFLOWD_VERBOSE}
    volumes:
      - ./gcp:/etc/mflowd
  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./misc:/etc/prometheus
    ports:
      - "9090:9090"
